disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - attributes
  - closure_spacing
  - colon
  - operator_usage_whitespace
  - fatal_error_message
  - trailing_closure
  - empty_count
  - function_default_parameter_at_end
  - prefer_self_in_static_references
  - identifier_name # 사용 전 Rule 확인 필요
  - sorted_imports # 알파벳 순서대로 임포트
  - duplicate_imports # 중복 임포트 제거

analyzer_rules:
  - unused_declaration

line_length:
  warning: 120
  error: 200

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length: 3

function_body_length:
  warning: 30
  error: 50

type_body_length:
  warning: 200
  error: 400

indentation:
  indentation_width: 4
  include_comments: true

colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

operator_usage_whitespace:
  severity: warning

type_name:
  validates_start_with_lowercase: warning

control_statement:
  severity: warning
  if_else: false

void_return:
  severity: warning
  
custom_rules:
  ios17_uikit_api_usage:
    name: "iOS 17+ UIKit API 사용"
    regex: '\b(UITextView\.TextLayoutManager|UIPasteControl|UIBackgroundConfiguration\.cornerRadius|SectionHeaderPinToVisibleBounds|UIView\.animationsEnabled|UIEditingOverlayViewController)\b'
    message: "이 UIKit API는 iOS 17 이상에서만 사용할 수 있습니다. 최소 지원 버전을 확인하거나 @available(iOS 17, *)로 감싸세요."
    severity: warning
